theme: jekyll-theme-dinky
title: "Analyzing and interpreting neural networks for NLP"
description: "Revealing the content of the neural black box: workshop on the analysis and interpretation of neural networks for Natural Language Processing."
show_downloads: false


